######################## default configuration ####################
baseURL = "https://langitketujuh.id/"
title = "LangitKetujuh"
defaultContentLanguage = "en" # id/en, default en
# post pagination
paginate = "6"
# post excerpt
summaryLength = "17"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
