# main menu
[[main]]
name = "Sistem Operasi"
identifier = "os"
URL = "os"
weight = 2

[[main]]
name = "Unduh"
identifier = "download"
URL = "os/download"
parent = "os"
weight = 1

[[main]]
name = "Panduan"
identifier = "guide"
URL = "https://panduan.langitketujuh.id"
parent = "os"
weight = 2

[[main]]
name = "Fitur"
identifier = "feature"
URL = "os/feature"
parent = "os"
weight = 3

[[main]]
name = "Peta Jalan"
identifier = "roadmap"
URL = "os/roadmap"
parent = "os"
weight = 4

# blog
[[main]]
name = "Warta"
identifier = "blog"
URL = "blog"
weight = 3

# vs
[[main]]
name = "Komparasi"
identifier = "vs"
URL = "vs"
weight = 4

[[main]]
name = "vs Ubuntu Studio"
identifier = "vs-ubuntu-studio"
URL = "vs/ubuntu-studio"
parent = "vs"
weight = 1

[[main]]
name = "vs Fedora Design Suite"
identifier = "vs-fedora-design-suite"
URL = "vs/fedora-design-suite"
parent = "vs"
weight = 2

[[main]]
name = "vs Manjaro-X Design Suite"
identifier = "vs-manjaro-x-design-suite"
URL = "vs/manjaro-x-design-suite"
parent = "vs"
weight = 3

# screenshot
[[main]]
name = "Cuplikan"
URL = "screenshot"
identifier = "screenshot"
weight = 5

[[main]]
name = "Ilustrasi dan Lukis Digital"
identifier = "illustration-and-digital-paint"
URL = "screenshot/illustration-and-digital-paint"
parent = "screenshot"
weight = 1

[[main]]
name = "2D/3D Animation Penuh Fitur"
identifier = "full-featured-2d-3d-animation"
URL = "screenshot/full-featured-2d-3d-animation"
parent = "screenshot"
weight = 2

[[main]]
name = "Font Kreator and Google Fonts"
identifier = "font-creator-dan-google-fonts"
URL = "screenshot/font-creator-dan-google-fonts"
parent = "screenshot"
weight = 3

[[main]]
name = "Mesin Game 2D/3D"
identifier = "game-engine-2d-3d"
URL = "screenshot/game-engine-2d-3d"
parent = "screenshot"
weight = 4

[[main]]
name = "Tata Letak dan Penerbitan Desktop"
identifier = "layout-and-desktop-publishing"
URL = "screenshot/layout-and-desktop-publishing"
parent = "screenshot"
weight = 5

[[main]]
name = "Fotografi dan Manajemen Gambar"
identifier = "photography-and-image-management"
URL = "screenshot/photography-and-image-management"
parent = "screenshot"
weight = 6

[[main]]
name = "Audio dan Video Non-linear"
identifier = "audio-and-video-non-linear"
URL = "screenshot/audio-and-video-non-linear"
parent = "screenshot"
weight = 7

[[main]]
name = "CAD dan gambar mekanik"
identifier = "cad-and-mechanical-drawing"
URL = "screenshot/cad-and-mechanical-drawing"
parent = "screenshot"
weight = 8

[[main]]
name = "Perlengkapan perkantoran profesional"
identifier = "professional-office-suite"
URL = "screenshot/professional-office-suite"
parent = "screenshot"
weight = 9

# sponsor
[[main]]
name = "Pendukung"
URL = "supporter"
weight = 6

# profile
[[main]]
name = "Profil"
identifier = "profile"
URL = "profile"
weight = 7

# contact
[[main]]
name = "Kontak"
URL = "profile/contact"
identifier = "contact"
parent = "profile"
weight = 1

# about us
[[main]]
name = "Tentang Kami"
identifier = "about-us"
URL = "profile/about-us"
parent = "profile"
weight = 2

# brand
[[main]]
name = "Brand"
identifier = "brand"
URL = "profile/brand"
parent = "profile"
weight = 3

# faq
[[main]]
name = "FAQ"
identifier = "faq"
URL = "faq"
weight = 8

# profile
[[footer_left]]
name = "Kontak"
URL = "profile/contact"
weight = 1

[[footer_left]]
name = "Kode sumber"
URL = "https://gitlab.com/langitketujuh"
weight = 2

[[footer_left]]
name = "Syarat & Ketentuan"
url = "tos"
weight = 3

[[footer_left]]
name = "Kebijakan pribadi"
url = "privacy"
weight = 4

[[footer_middle]]
name = "LangitKetujuh"
URL = "/"
weight = 1

[[footer_right]]
name = "Komunitas"
URL = "community"
weight = 1

[[footer_right]]
name = "Umpan balik"
URL = "feedback"
weight = 2

[[footer_right]]
name = "Kerjasama"
URL = "cooperation"
weight = 3

[[footer_right]]
name = "Peta jalan"
URL = "os/roadmap"
weight = 5

[[footer_right]]
name = "Ikuti kami"
URL = "https://follow.langitketujuh.id"
weight = 6
