# Default parameters
logo = "images/icon.webp"
logo_width = "60px"
description = "Distribution for designers, illustrators, animators, publishers, photographers, font creators and game designers. Using glibc & musl libc, rolling releases, runit init and KDE desktop environments."
author = "LangitKetujuh"
image = "images/icon.webp" # this image will be used as fallback if a page has no image of its own

# Contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Favicon
favicon = "images/icons/favicon.ico"
icon16 = "images/icons/icon-16x16.png"
icon32 = "images/icons/icon-32x32.png"
icon144 = "images/icons/icon-144x144.png"
icon152 = "images/icons/icon-152x152.png"
icon192 = "images/icons/icon-192x192.png"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Contribute"
link = "contribute"

# Cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
# Social site
[[social]]
title = "email"
icon = "fas fa-envelope"
link = "mailto:langitketujuh.id@proton.me"

[[social]]
title = "gitlab"
icon = "fab fa-gitlab"
link = "https://gitlab.com/langitketujuh"

[[social]]
title = "gitlab"
icon = "fab fa-github"
link = "https://github.com/langitketujuh"

[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://facebook.com/langitketujuh.id"

[[social]]
title = "instagram"
icon = "fab fa-instagram"
link = "https://instagram.com/langitketujuh.id"

[[social]]
title = "telegram"
icon = "fab fa-telegram"
link = "https://t.me/langitketujuh_id"

[[social]]
title = "whatsapp"
icon = "fab fa-whatsapp"
link = "https://wa.me/message/RN5NNCNHNEY6B1"
