######################## default configuration ####################
baseURL = "https://langitketujuh.netlify.app/"
title = "LangitKetujuh OS"
theme = "bigspring"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Blog"
URL = "blog"
weight = 1

[[menu.main]]
name = "Unduh"
URL = "unduh"
weight = 2

[[menu.main]]
name = "Fitur"
URL = "fitur"
weight = 3

[[menu.main]]
name = "Kabari"
URL = "kabari"
weight = 4

[[menu.main]]
name = "FAQ"
URL = "faq"
weight = 5

# komunitas 
[[menu.komunitas]]
name = "Tentang Kami"
URL = "tentang-kami"
weight = 1

# produk 
[[menu.produk]]
name = "LangitKetujuh OS"
URL = "/"
weight = 1

[[menu.produk]]
name = "Impress Template"
URL = "impress"
weight = 2

[[menu.produk]]
name = "Online Course"
URL = "online-course"
weight = 3

# dukungan 
[[menu.dukungan]]
name = "Peraturan dan kondisi"
URL = "peraturan-kondisi"
weight = 1

[[menu.dukungan]]
name = "FAQ"
URL = "faq"
weight = 2

[[menu.dukungan]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 3

#################### default parameters ################################
[params]
logo = "gambar/logo-l7.svg"
logo_width = "130px"
logo_footer = "gambar/logo-l7.svg"
logo_width_footer = "90px"
# Meta data
description = "Distribusi GNU/Linux untuk desainer, ilustrator, animator, publisher, fotografer, dan game desainer. Dibangun dengan musl rolling rilis stabil, runit, dan KDE."
author = "langitketujuh"
# contact form action
contact_form_action = "https://formspree.io/f/xeqpgqda" # contact form works with https://formspree.io

########### footer content ##########
footer_content = "Distribusi GNU/Linux untuk desainer, ilustrator, animator, publisher, fotografer, dan game desainer. Dibangun dengan musl rolling rilis stabil, runit, dan KDE."
# copyright
copyright = "2020 [LangitKetujuh GNU/Linux](https://gitlab.com/langitketujuh). 2020 [VoidLinux kontributor](https://github.com/orgs/void-linux/people). Hak Cipta 2008-2018 [Juan RP](https://gitlab.com/xtraeme) dan kontributor. [Linux®](https://www.linuxfoundation.org/programs/legal/trademark/attribution) telah didaftarkan dengan merek dagang dari Linus Torvalds. [KDE® and the K Desktop Environment® logo](https://kde.org/media/images/trademark_kde_gear_black_logo.png) telah didaftarkan dengan branding [KDE e.V](https://ev.kde.org/). Template oleh [Themefisher](https://themefisher.com/). dikembangkan oleh [Gethugothemes](https://gethugothemes.com/). Ilustrasi oleh [whoooa](https://www.whoooa.rocks/) dan [LangitKetujuh GNU/Linux](https://gitlab.com/langitketujuh)."

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "Unduh v0.3"
link = "unduh"

  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://facebook/langitketujuh.id"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/langitketujuh"

[[params.social]]
title = "skype"
icon = "ti-skype" # themify icon : https://themify.me/themify-icons
link = "https://skype.com/langitketujuh"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://linkedin.com/langitketujuh"
