# DEFAULT

baseURL = "https://langitketujuh.id/"
title = "LangitKetujuh OS | Pilihan Tepat untuk Desainer dan Pengguna Desktop"
languageName = "Id"
languageCode = "en-US"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

# NAVIGASI

# menu utama
[[menu.main]]
name = "Blog"
URL = "blog"
weight = 1

[[menu.main]]
name = "Unduh"
URL = "unduh"
weight = 2

[[menu.main]]
name = "Fitur"
URL = "fitur"
weight = 3

[[menu.main]]
name = "Cuplikan"
URL = "cuplikan"
weight = 4

[[menu.main]]
name = "Kabari"
URL = "kabari"
weight = 5

[[menu.main]]
name = "FAQ"
URL = "faq"
weight = 6

# profil
[[menu.profil]]
name = "Tentang Kami"
URL = "tentang-kami"
weight = 1

[[menu.profil]]
name = "Kode Sumber"
URL = "https://gitlab.com/langitketujuh"
weight = 2

# produk 
[[menu.produk]]
name = "LangitKetujuh OS"
URL = "/"
weight = 1

# dukungan
[[menu.dukungan]]
name = "Finansial"
URL = "finansial"
weight = 1

[[menu.dukungan]]
name = "Feedback"
URL = "feedback"
weight = 2

[[menu.dukungan]]
name = "Peraturan layanan"
URL = "peraturan-layanan"
weight = 3

[[menu.dukungan]]
name = "Kebijakan Privasi"
URL = "kebijakan-privasi"
weight = 4

# PARAMETER

[params]
  logo = "gambar/logo-l7.svg"
  logo_width = "130px"
  logo_footer = "gambar/logo-l7.svg"
  logo_width_footer = "90px"
  author = "LangitKetujuh ID"
  opengraphimage = "gambar/thumbnail.webp"
  description = "Distribusi GNU/Linux untuk desainer, ilustrator, animator, publisher, fotografer, dan game desainer. Menggunakan musl libc, rolling rilis, runit, dan KDE lingkungan desktop. "

# FOOTER

footer_content = "Pilihan Tepat untuk Desainer dan Pengguna Desktop"
# copyright
copyright = "2020 [LangitKetujuh ID](https://gitlab.com/langitketujuh). 2020 [VoidLinux kontributor](https://github.com/orgs/void-linux/people). Hak Cipta 2008-2018 [Juan RP](https://gitlab.com/xtraeme) dan kontributor. [Linux®](https://www.linuxfoundation.org/programs/legal/trademark/attribution) telah didaftarkan dengan merek dagang dari Linus Torvalds. [KDE® and the K Desktop Environment® logo](https://kde.org/media/images/trademark_kde_gear_black_logo.png) telah didaftarkan dengan branding [KDE e.V](https://ev.kde.org/). Template oleh [Themefisher](https://themefisher.com/). Dikembangkan oleh [Gethugothemes](https://gethugothemes.com/). Ilustrasi oleh [Hervy Qurrotul](https://hervyqa.com)."

# PRELOADER

[params.preloader]
enable = true
preloader = "gambar/preloader.svg" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "Donasi"
link = "donasi"

# SOSIAL MEDIA

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://instagram.com/langitketujuh.id"

[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://facebook/langitketujuh.id"

#[[params.social]]
#title = "twitter"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "https://twitter.com/langitketujuh.id"

#[[params.social]]
#title = "skype"
#icon = "ti-skype" # themify icon : https://themify.me/themify-icons
#link = "https://skype.com/langitketujuh.id"
