# DEFAULT

baseURL = "https://langitketujuh.id/"
title = "LangitKetujuh OS"
languageName = "Id"
languageCode = "en-US"
# post pagination
paginate = "9"
# post excerpt
summaryLength = "17"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/drag/drag.min.js"

# NAVIGASI

# menu utama
[[menu.main]]
name = "Unduh ⚡"
identifier = "unduh"
URL = "unduh"
weight = 1

[[menu.main]]
name = "Fitur"
identifier = "fitur"
URL = "fitur"
weight = 2

[[menu.main]]
name = "Blog"
identifier = "blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Panduan 💡"
URL = "https://panduan.langitketujuh.id"
weight = 4

[[menu.main]]
name = "Komparasi"
identifier = "komparasi"
URL = "komparasi"
weight = 5

[[menu.main]]
name = "Vs Ubuntu Studio"
identifier = "vs-ubuntu-studio"
URL = "komparasi/vs-ubuntu-studio"
parent = "komparasi"
weight = 1

[[menu.main]]
name = "Vs Fedora Design Suite"
identifier = "vs-fedora-design-suite"
URL = "komparasi/vs-fedora-design-suite"
parent = "komparasi"
weight = 2

[[menu.main]]
name = "Vs Manjaro-X Design Suite"
identifier = "vs-manjaro-x-design-suite"
URL = "komparasi/vs-manjaro-x-design-suite"
parent = "komparasi"
weight = 3

[[menu.main]]
name = "Cuplikan"
URL = "cuplikan"
identifier = "cuplikan"
weight = 6

[[menu.main]]
name = "Ilustrasi dan Lukis Digital"
identifier = "ilustrasi-dan-lukis-digital"
URL = "cuplikan/ilustrasi-dan-lukis-digital"
parent = "cuplikan"
weight = 1

[[menu.main]]
name = "Animasi 2D/3D Penuh Fitur"
identifier = "animasi-2d-3d-penuh-fitur"
URL = "cuplikan/animasi-2d-3d-penuh-fitur"
parent = "cuplikan"
weight = 2

[[menu.main]]
name = "Font Kreator dan Google Fonts"
identifier = "font-kreator-dan-google-fonts"
URL = "cuplikan/font-kreator-dan-google-fonts"
parent = "cuplikan"
weight = 3

[[menu.main]]
name = "Mesin Game 2D/3D"
identifier = "mesin-game-2d-3d"
URL = "cuplikan/mesin-game-2d-3d"
parent = "cuplikan"
weight = 4

[[menu.main]]
name = "Desktop Publishing"
identifier = "desktop-publishing"
URL = "cuplikan/desktop-publishing"
parent = "cuplikan"
weight = 5

[[menu.main]]
name = "Fotografi dan Manajemen Gambar"
identifier = "fotografi-dan-manajemen-gambar"
URL = "cuplikan/fotografi-dan-manajemen-gambar"
parent = "cuplikan"
weight = 6

[[menu.main]]
name = "Audio dan Video Non-linear"
identifier = "audio-dan-video-non-linear"
URL = "cuplikan/audio-dan-video-non-linear"
parent = "cuplikan"
weight = 7

[[menu.main]]
name = "CAD dan menggambar mekanik"
identifier = "cad-dan-menggambar-mekanik"
URL = "cuplikan/cad-dan-menggambar-mekanik"
parent = "cuplikan"
weight = 8

[[menu.main]]
name = "Perlengkapan Perkantoran"
identifier = "perlengkapan-perkantoran"
URL = "cuplikan/perlengkapan-perkantoran"
parent = "cuplikan"
weight = 9

[[menu.main]]
name = "Produktifitas Dasar"
identifier = "produktifitas-dasar"
URL = "cuplikan/produktifitas-dasar"
parent = "cuplikan"
weight = 10

[[menu.main]]
name = "Kabari"
URL = "kabari"
weight = 7

[[menu.main]]
name = "FAQ"
URL = "faq"
weight = 8

# profil
[[menu.profil]]
name = "Tentang Kami"
URL = "tentang-kami"
weight = 1

[[menu.profil]]
name = "Kode Sumber"
URL = "https://gitlab.com/langitketujuh"
weight = 2

[[menu.profil]]
name = "Peraturan layanan"
URL = "peraturan-layanan"
weight = 3

[[menu.profil]]
name = "Kebijakan Privasi"
URL = "kebijakan-privasi"
weight = 4

# produk 
[[menu.produk]]
name = "LangitKetujuh OS"
URL = "/"
weight = 1

# dukungan
#[[menu.dukungan]]
#name = "Finansial"
#URL = "finansial"
#weight = 1

[[menu.dukungan]]
name = "Komunitas"
URL = "komunitas"
weight = 1

[[menu.dukungan]]
name = "Feedback"
URL = "feedback"
weight = 2

[[menu.dukungan]]
name = "Kerjasama"
URL = "kerjasama"
weight = 3

# PARAMETER

[params]
  logo = "media/beranda/logo.webp"
  logo_width = "70px"
  logo_footer = "media/beranda/logo.webp"
  logo_width_footer = "60px"
  author = "LangitKetujuh ID"
  image = "media/beranda/thumbnail.jpg"
  opengraphimage = "media/beranda/thumbnail.jpg"
  description = "Distribusi GNU/Linux untuk desainer, ilustrator, animator, publisher, fotografer, font kreator dan game desainer. Menggunakan glibc & musl libc, rilis bergulir, runit init dan KDE lingkungan desktop."

# FOOTER

footer_content = "Pilihan Tepat untuk Desainer dan Pengguna Desktop"
# copyright
copyright = "2021 [Hervy Qurrotul A. R.](mailto:hervyqa@pm.me) dan [LangitKetujuh kontributor](https://gitlab.com/langitketujuh). 2020 [VoidLinux kontributor](https://github.com/orgs/void-linux/people) dan 2008-2018 [Juan RP](https://gitlab.com/xtraeme). [Linux®](https://www.linuxfoundation.org/programs/legal/trademark/attribution) telah didaftarkan dengan merek dagang dari Linus Torvalds. [KDE® and the K Desktop Environment® logo](https://kde.org/media/images/trademark_kde_gear_black_logo.png) telah didaftarkan dengan branding [KDE e.V](https://ev.kde.org/). Template oleh [Themefisher](https://themefisher.com/). Dikembangkan oleh [Gethugothemes](https://gethugothemes.com/)."

# PRELOADER

[params.preloader]
enable = true
preloader = "media/beranda/preloader.svg" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "Donasi ✨"
link = "donasi"

# SOSIAL MEDIA

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://instagram.com/langitketujuh.id"

[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://facebook.com/langitketujuh.id"

#[[params.social]]
#title = "twitter"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "https://twitter.com/langitketujuh.id"

#[[params.social]]
#title = "skype"
#icon = "ti-skype" # themify icon : https://themify.me/themify-icons
#link = "https://skype.com/langitketujuh.id"
