[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.91.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.91.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.webp" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "https://langitketujuh.netlify.app/*"
  to = "https://langitketujuh.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://langitketujuh.netlify.app/*"
  to = "https://langitketujuh.id/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://langitketujuh.id/wa"
  to = "https://api.whatsapp.com/send/?phone=6282131146131"
  status = 301
  force = true

[[redirects]]
  from = "https://langitketujuh.id/mentari-umsida"
  to = "https://chat.whatsapp.com/Ks6wPK7J9jv3k4YJDHmer5"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
