#!/usr/bin/env bash

info_msg() {
    printf "\033[1m$@\n\033[m"
}

die() {
    info_msg "ERROR: $@"
}

# Check for root permissions.
if [ "$(id -u)" -ne 0 ]; then
    die "Must be run as root, exiting..."
fi

# download
wget 'https://gitlab.com/langitketujuh/template/-/raw/master/srcpkgs/l7-export/files/l7-export' -O /usr/bin/l7-export ;

# install
chmod +x /usr/bin/l7-export

# check
if ls -lh /usr/bin/l7-export > /tmp/checkers >/dev/null 2>&1; then
  echo -e "\033[1;36m[FINISH]\033[0m l7-export is already installed!"
  else
  echo -e "\033[1;33m[FAILED]\033[0m l7-export is not already installed!"
  exit;
fi
