#!/usr/bin/env bash

info_msg() {
    printf "\033[1m$@\n\033[m"
}

die() {
    info_msg "ERROR: $@"
}

# Check for root permissions.
if [ "$(id -u)" -ne 0 ]; then
    die "Must be run as root, exiting..."
fi

# download
wget 'https://gitlab.com/langitketujuh/script/-/raw/master/l7-tools' -O /usr/bin/l7-tools ;

# install
chmod +x /usr/bin/l7-tools

# check
if ls -lh /usr/bin/l7-tools > /tmp/checkers >/dev/null 2>&1; then
  echo -e "\033[1;36m[FINISH] l7-tools is already installed.\033[0m"
  else
  echo -e "\033[1;33m[FAILED] l7-tools is not already installed!\033[0m"
  exit;
fi
