---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/sk-feedback
  label: Sk feedback
  create: all
  match: "**/*"
- type: directory
  path: content/404
  label: '404'
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/cuplikan
  label: Cuplikan
  create: all
  match: "**/*"
- type: directory
  path: content/faq
  label: Faq
  create: all
  match: "**/*"
- type: directory
  path: content/feedback
  label: Feedback
  create: all
  match: "**/*"
- type: directory
  path: content/finansial
  label: Finansial
  create: all
  match: "**/*"
- type: directory
  path: content/fitur
  label: Fitur
  create: all
  match: "**/*"
- type: directory
  path: content/kabari
  label: Kabari
  create: all
  match: "**/*"
- type: directory
  path: content/kebijakan-privasi
  label: Kebijakan privasi
  create: all
  match: "**/*"
- type: directory
  path: content/kerjasama
  label: Kerjasama
  create: all
  match: "**/*"
- type: directory
  path: content/komparasi
  label: Komparasi
  create: all
  match: "**/*"
- type: directory
  path: content/lite
  label: Lite
  create: all
  match: "**/*"
- type: directory
  path: content/peraturan-layanan
  label: Peraturan layanan
  create: all
  match: "**/*"
- type: directory
  path: content/pro-glibc
  label: Pro glibc
  create: all
  match: "**/*"
- type: directory
  path: content/pro-musl
  label: Pro musl
  create: all
  match: "**/*"
- type: directory
  path: content/pro
  label: Pro
  create: all
  match: "**/*"
- type: directory
  path: content/sk-kerjasama
  label: Sk kerjasama
  create: all
  match: "**/*"
- type: directory
  path: content/sk-pro
  label: Sk pro
  create: all
  match: "**/*"
- type: directory
  path: content/tentang-kami
  label: Tentang kami
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
